name: Build & Test & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Clone git repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencie
        run: npm install
      - name: Start the application
        # Run the application in the background in order to free up the console.
        run: npm start &
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repository
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Start the application
        run: npm start &
      - name: Run integration tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_TOKEN }}
          api-key: ${{ secrets.API_KEY }}
