resource_group_name      = "task-board-rg"
resource_group_location  = "West Europe"
service_plan_name        = "task-board-sp"
linux_web_app_name       = "task-board-lwa"
source_control_repo_url  = "https://github.com/deyordanov/Terraform3"
mssql_server_name        = "task-board-dbs"
mssql_database_name      = "task-board-db"
mssql_firewall_rule_name = "task-board-dbf"