version: '3.8'

services:
  web_app:
    depends_on:
      - sqlserver
    build: 
      dockerfile: ./TaskBoard.WebApp/Dockerfile
    ports:
      - 5000:80
    restart: on-failure
    networks:
      - taskboard_network
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SoftUn!2024
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - taskboard_network

volumes:
  sqldata:
networks:
  taskboard_network: